name: run_script

on: 
  schedule:
  - cron: '0 */3 * * *'
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "firebase-connection.json"
          json: ${{ secrets.FB_CONECT_JSON }}
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: execute py script # run file
        run: |
          python main_scrapper.py
